'use strict';

// tests for getData
// Generated by serverless-jest-plugin

const mod = require('../functions/getUser/index');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('getData', () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      const body = JSON.parse(response.body);
      expect(body).toHaveProperty('user.firstName', 'Oba');
    });
  });
});
