'use strict';

// tests for myFunction
// Generated by serverless-jest-plugin

const mod = require('../functions/hello/index');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('myFunction', () => {
  beforeAll(done => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then(response => {
      expect(JSON.parse(response.body)).toHaveProperty(
        'message',
        'Go Serverless v1.0! Your function executed successfully!'
      );
    });
  });
});
